---
- name: Copy MySQL master "{{ master_file }}" master file
  hosts: node1
  become: true

  tasks: 
    - name: copy pgpool.conf
      copy: 
        src: "{{ master_path }}/{{ master_file }}"
        dest: /tmp/{{ master_file }}
        owner: root
        group: root
        mode: 0764