---
- hosts: nodedb
  any_errors_fatal: true
  roles:
  - role: common

- hosts: nodedb
  any_errors_fatal: true
  roles:
  - role: backend  

- hosts: node1
  any_errors_fatal: true
  roles:
  - role: conf_inno