---
# This step for creating volume group for data and binlog dir
- include: os_vgm.yml

# This step for creating logical volume for data and binlog dir
- include: os_lvm.yml

# This step for mounting LVM to data directory
- include: os_mount.yml

# This step for create mysql user and group
- include: os_user.yml

# This step for install prerequisite of mysql installation
- include: my_prereq.yml

# This step for copy master file to all backend database1  
- include: my_extract.yml

# This step for Add mysql bin to root profile
- include: my_env.yml

# This step for init mysql 
- include: my_init.yml

# Secure installation 
- include_role:
    name: my_secure

# Create icuser user
- include: my_create_user.yml    