---
# This step for creating volume group for data and binlog dir
- include: os_vgm.yml

# This step for creating logical volume for data and binlog dir
- include: os_lvm.yml

# This step for mounting LVM to data directory
- include: os_mount.yml

# This step for create mysql user and group
- include: os_user.yml

# This step for copy master file to all backend database1  
- include: my_extract.yml