---
- name: Add ic_user for administrating Cluster
  community.mysql.mysql_user:
    name: icuser
    host: "{{ icuser_host }}"
    password: "{{ icuser_pass }}"
    priv: '*.*:ALL,GRANT'
    state: present