---
- name: Add my.cnf for client to root dir
  ansible.builtin.template:
    src: my.client.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0644

- name: Add ic_user for administrating Cluster
  mysql_user:
    name: icuser
    host: "{{ icuser_host }}"
    password: "{{ icuser_pass }}"
    priv: '*.*:ALL,GRANT'
    state: present