---
- name: Copy MySQL master file
  copy: 
    src: "{{ master_path }}/{{ master_file }}"
    dest: /tmp/{{ master_file }}
    owner: root
    group: root
    mode: 0764

- name: Copy MySQL Shell master file
  copy: 
    src: "{{ master_shell_path }}/{{ master_shell_file }}"
    dest: /tmp/{{ master_shell_file }}
    owner: root
    group: root
    mode: 0764

- name: Create a /usr/local directory if it does not exist
  ansible.builtin.file:
    path: /usr/local
    state: directory
    mode: '0755'    

- name: Extract MySQL master file
  ansible.builtin.unarchive:
    src: /tmp/{{ master_file }}
    dest: /usr/local

- name: Change file ownership, group and permissions for MySQL master folder
  ansible.builtin.file:
    path: /usr/local/{{ master_folder }}
    owner: mysql
    group: mysql
    mode: '0755'    

- name: Create a symbolic link for MySQL master folder
  ansible.builtin.file:
    src: /usr/local/{{ master_folder }}
    dest: /usr/local/mysql
    owner: mysql
    group: mysql
    state: link    

- name: Extract MySQL Shell master file
  ansible.builtin.unarchive:
    src: /tmp/{{ master_shell_file }}
    dest: /tmp

- name: Install a '{{ master_shell_name }}' package
  apt:
    deb: /tmp/{{ master_shell_name }}

- name: Copy MySQL to init for register
  copy: 
    src: /usr/local/mysql/support-files/mysql.server
    dest: /etc/init.d/
    owner: root
    group: root

- name: Create a symbolic link for mysql.server to init.d
  ansible.builtin.file:
    src: /etc/init.d/mysql.server
    dest: /etc/rc3.d/S99mysql.server
    owner: root
    group: root
    state: link

- name: Create /data/mysql directory if it does not exist
  ansible.builtin.file:
    path: /data/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'

- name: Create /binlog/mysql directory if it does not exist
  ansible.builtin.file:
    path: /binlog/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'    