---
- name: Add mysql bin to root profile
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644

- name: Initiate Galera Database
  shell: /usr/local/mysql/bin/mysqld --defaults-file=/etc/my.cnf --user=mysql --initialize-insecure
  args:
    warn: false

- name: Start service mysql
  ansible.builtin.service:
    name: mysql.server
    state: started