---
- name: Check if database already created
  stat:
    path: /data/mysql/mysql
  register: mysql_exists

- name: Check if database already created and started
  stat:
    path: /data/mysql/mysql.sock
  register: mysql_sock_exists  

- name: Add mysql bin to root profile
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
  when: not mysql_exists.stat.exists

- name: Initiate Galera Database
  shell: /usr/local/mysql/bin/mysqld --defaults-file=/etc/my.cnf --user=mysql --initialize-insecure
  args:
    warn: false
  when: not mysql_exists.stat.exists    

- name: Enable service mysql
  service:
    name: mysql.server
    enabled: yes

- name: Start service mysql
  service:
    name: mysql.server
    state: started
  when: not mysql_sock_exists.stat.exists    