---
- name: Install libaio prereq
  apt:
    name: libaio1
    state: present

- name: Install numactl prereq
  apt:
    name: numactl
    state: present 

- name: Install libtinfo5 prereq
  apt:
    name: libtinfo5
    state: present 

- name: Adds Python MySQL support on Debian/Ubuntu
  apt: pkg="python-mysqldb" state=present
    when: ansible_os_family == 'Debian'

- name: Adds Python MySQL support on RedHat/CentOS
  yum: name=MySQL-python state=present
    when: ansible_os_family == 'RedHat'    