---
- name: Install libaio prereq
  apt:
    name: libaio1
    state: present

- name: Install numactl prereq
  apt:
    name: numactl
    state: present 

- name: Install libtinfo5 prereq
  apt:
    name: libtinfo5
    state: present 

- name: Adds Python MySQL support on Debian/Ubuntu
  apt: 
    name: python-mysqldb 
    state: present