---
- name: Install libaio prereq
  apt:
    name: libaio1
    state: present

- name: Install numactl prereq
  apt:
    name: numactl
    state: present 

- name: Install libtinfo6 prereq
  apt:
    name: libtinfo6
    state: present 

- name: Symlink for libtinfo6 to libtinfo5
  file:
    src: /usr/lib/x86_64-linux-gnu/libtinfo.so.6
    dest: /usr/lib/x86_64-linux-gnu/libtinfo.so.5
    owner: root
    group: root
    state: link    

- name: Install pip3 prereq
  apt:
    name: python3-pip
    state: present  

- name: Install pyMySQL
  pip:
    name: pymysql
    state: present